import CMS from 'decap-cms-app';
import uploadcare from 'decap-cms-media-library-uploadcare';
import cloudinary from 'decap-cms-media-library-cloudinary';

import AboutPagePreview from './preview-templates/AboutPagePreview';
import IndexPagePreview from './preview-templates/IndexPagePreview';
import CommitteePagePreview from './preview-templates/CommitteePagePreview';
import GivePagePreview from './preview-templates/GivePagePreview';
import ChristmasForChristPagePreview from './preview-templates/ChristmasForChristPagePreview';
import MinistriesPagePreview from './preview-templates/MinistriesPagePreview';
import AffiliationPagePreview from './preview-templates/AffiliationPagePreview';
import ContactUsPagePreview from './preview-templates/ContactUsPagePreview';
import ApplicationsPagePreview from './preview-templates/ApplicationsPagePreview';
import DaughterWorkPagePreview from './preview-templates/DaughterWorkPagePreview';
import NAMStatusPagePreview from './preview-templates/NAMStatusPagePreview';
import AffiliationApplicationPagePreview from './preview-templates/AffiliationApplicationPagePreview';
import PolicyFormPagePreview from './preview-templates/PolicyFormPagePreview';
import ResourcesPagePreview from './preview-templates/ResourcesPagePreview';

CMS.registerMediaLibrary(uploadcare);
CMS.registerMediaLibrary(cloudinary);
CMS.registerPreviewTemplate('index', IndexPagePreview);
CMS.registerPreviewTemplate('about', AboutPagePreview);
CMS.registerPreviewTemplate('committee', CommitteePagePreview);
CMS.registerPreviewTemplate('give', GivePagePreview);
CMS.registerPreviewTemplate('affiliation', AffiliationPagePreview);
CMS.registerPreviewTemplate('ministries', MinistriesPagePreview);
CMS.registerPreviewTemplate('contact-us', ContactUsPagePreview);
CMS.registerPreviewTemplate('christmas-for-christ', ChristmasForChristPagePreview);
CMS.registerPreviewTemplate('applications', ApplicationsPagePreview);
CMS.registerPreviewTemplate('daughter-work', DaughterWorkPagePreview);
CMS.registerPreviewTemplate('nam-status', NAMStatusPagePreview);
CMS.registerPreviewTemplate('affiliation-application', AffiliationApplicationPagePreview);
CMS.registerPreviewTemplate('policy-form', PolicyFormPagePreview);
CMS.registerPreviewTemplate('resources', ResourcesPagePreview);
