services:
  gatsby-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socalnam-website
    ports:
      - "8000:8000"  # Gatsby dev server
      - "8001:8001"  # GraphQL playground
    volumes:
      # Mount the entire project directory
      - .:/app
      # Use named volumes for node_modules to improve performance
      # and avoid conflicts between host and container
      - node_modules:/app/node_modules
      - gatsby_cache:/app/.cache
      - gatsby_public:/app/public
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
    stdin_open: true
    tty: true
    command: npx gatsby develop -H 0.0.0.0

volumes:
  node_modules:
  gatsby_cache:
  gatsby_public:
